

THORSANVIL_ROOT			= $(realpath ../)
CXXFLAGS                       += -DCLOUD_USE_CPLUSPLUS11 -Wall -Wextra -Wstrict-aliasing -pedantic -Werror -Wunreachable-code -Wno-long-long
LINK_LIBS				= Json
TARGET					= Serialize.slib
UNITTEST_LINK_LIBS		= Json

include ${THORSANVIL_ROOT}/build/tools/Makefile


