
THORSANVIL_ROOT				?= $(realpath ../)
TARGET						= ThorsLogging fast_float Serialize ThorsCrypto ThorsStorage ThorsSocket ThorsMongo NisseServer NisseHTTP NisseLib ThorsSlack ThorsMug TestExtra.NotWin Mug.NotWin


include $(THORSANVIL_ROOT)/build/tools/Project.Makefile

