THORSANVIL_ROOT				?= $(realpath ../)
SUBDIRS						= ThorsLogging fast_float Serialize ThorsCrypto ThorsStorage ThorsSocket ThorsMongo NisseServer NisseHTTP NisseLib ThorsSlack ThorsMug NisseBolt TestExtra.NotWin Mug.NotWin


include $(THORSANVIL_ROOT)/build/tools/Makefile
